### ISSUE TITLE
Training arguments for FedEx

### ISSUE THREAD

**Issue by HaokunChen245** [mkhodak/FedEx#1]
Hi guys,

thanks for sharing the code. Could you please also share the arguments used for training FedEx with different datasets?

Thanks in advance.

**Comment by mkhodak** [comment]
Thank you for your interest. All datasets use the same commands, just different scripts (`cifar.py`, `femnist.py`, and `shakespeare.py`). To run on the i.i.d. version of FEMNIST and Shakespeare (instead of non-i.i.d., the default) use option `--iid`. To run SHA (instead of random search, the default) use options `--elim 3 --eval 16`. To run FedEx (instead of FedAvg, the default) use options `--configs -1 --eps 0.1 --sched aggressive`.

**Comment by HaokunChen245** [comment]
Thanks for your quick reply! I will close this issue.
